version: "3.9"

services:
    # PHP Service
    rest_api:
        build:
            args:
                user: Polash
                uid: 1000
            context: .
            dockerfile: .docker/Dockerfile
        image: rest_api
        container_name: rest_api
        restart: unless-stopped
        working_dir: /var/www/
        tty: true
        environment:
            SERVICE_NAME: app
            SERVICE_TAGS: dev
        volumes:
            - ./:/var/www
            - ./.docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - rest_api_network

    # MySQL Service
    rest_api_db:
        image: mysql:8.0
        container_name: rest_api_db
        restart: unless-stopped
        ports:
            - "${DOCKER_DB_PORT}:3306"
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - rest_api_mysql_data:/var/lib/mysql
        networks:
            - rest_api_network

    # Nginx Service
    rest_api_nginx:
        image: nginx:alpine
        container_name: rest_api_nginx
        restart: unless-stopped
        tty: true
        ports:
            - "${DOCKER_APP_PORT}:80"
            - "${DOCKER_APP_SSL_PORT}:443"
        volumes:
            - ./:/var/www
            - ./.docker/nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - rest_api_network

    # phpMyAdmin Service
    rest_api_phpmyadmin:
        image: phpmyadmin/phpmyadmin
        restart: unless-stopped
        container_name: rest_api_phpmyadmin
        depends_on:
            - rest_api_db
        ports:
            - "${DOCKER_PHPMYADMIN_PORT}:80"
        environment:
            PMA_HOST: rest_api_db
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            UPLOAD_LIMIT: 50M
        networks:
            - rest_api_network

    # Redis Cache Service
    rest_api_redis_cache:
        image: redis:alpine
        restart: always
        container_name: rest_api_redis_cache
        ports:
            - "${DOCKER_REDIS_PORT}:6379"
        command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
        volumes:
            - rest_api_cache:/data
        networks:
            - rest_api_network

# Docker Networks
networks:
    rest_api_network:
        driver: bridge

# Volumes
volumes:
    rest_api_mysql_data:
    rest_api_cache:
